@Password_manager_api_HostAddress = https://localhost:7074
@Password_manager_api_HostAddress = http://localhost:5230

POST {{Password_manager_api_HostAddress}}/api/accountsitems
Content-Type: application/json

{
  "Id": 1,
  "Email": "testas@gmail.com",
  "Password": "Tomato",
  "CreatedAt": 1
}

###

GET {{Password_manager_api_HostAddress}}/api/accountsitems

###
